### PR TITLE
Add taxonomy in workflow diagram

### PR DESCRIPTION
**Pull request by Darcy220606**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/funcscan/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/funcscan _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by jasmezz — COMMENTED** [review]
- For the annotation part (prokka etc.), the sequences actually come from gunzip, only tax. classification from MMseqs2. Atm. it looks like everything comes from tax. classification. It would be more correct to merge it like in my screenshot below.
- I would call it "taxonomic classification".
- I am not sure if it's better to write "MMseqs2" into the workflow and put "Taxonomic classification" into the legend (and give it a colour). That would be consistent to the 3 other subworkflows which have all their tools listed as stations. On the other hand, MMseqs2 is our only tool for the tax. class. and makes the diagram more clean like you put it. No strong opinion yet.
image

**Comment by jasmezz** [comment]
Maybe yours is actually better. Because the 3 coloured subworkflows also come from the tax. class. station, so maybe let the annotation seqs come out here as well to keep it consistent.

**Comment by Darcy220606** [comment]
@jasmezz Hmm, I would suggest to have the three workflows coming out of the taxa classification 'stop' as that is how funcscan is now 'built' and yes I agree with u to rename the stop to mmseqs2 and colour the circle and add the coloured circle to the legend and add taxonomic classification there.

**Comment by jfy133** [comment]
The current lines don't make sense to me, the mmseqs2 files don't go into the ARG/AMP/BGC workflows.

I would rather do something like this (please don't laugh at my 60second inkscape skills :grimacing: )

**Comment by Darcy220606** [comment]
> The current lines don't make sense to me, the mmseqs2 files don't go into the ARG/AMP/BGC workflows.
> 
> I would rather do something like this (please don't laugh at my 60second inkscape skills 😬 )
> 
> image

Nice drawing @jfy133 .... Yeah ok, thats actually closer to how it is setup. So i give it another colour and add another line in the legend for taxonomic classification. Back to the drawing board 🎨 👩🏽‍🎨

**Comment by jfy133** [comment]
> Nice drawing @jfy133 .... Yeah ok, thats actually closer to how it is setup. So i give it another colour and add another line in the legend for taxonomic classification. Back to the drawing board 🎨 👩🏽‍🎨

Oooooor @Darcy220606 same black colour as annotation but different dashed line?

**Comment by jasmezz** [comment]
Superseded by #361

**Pull request closed without merging**
